# Generated by Django 3.2.5 on 2022-05-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sid',
            new_name='contact',
        ),
    ]
